swagger: "2.0"

info:
  title: API Documentation
  version: 1.0.0

tags:
  - name: Category
    description: 📁 APIs related to Category.

paths:

  /categories:
    get:
      tags:
        - Category
      summary: Get all categories
      description: |
        Retrieve a list of all categories.
        Categories are returned without their `_id` field.
      responses:
        '200':
          description: A list of categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/definitions/Category'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

  /create-category:
    post:
      tags:
        - Category
      summary: Create a new category
      description: |
        Create a new category with the provided details.
        The `name` field is required, and a unique `slug` will be generated automatically.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the category.
                  example: "Electronics"
                des:
                  type: string
                  description: The description of the category.
                  example: "All electronic gadgets and devices."
                icon:
                  type: string
                  description: The icon for the category.
                  example: "fa-electronics"
                parent:
                  type: string
                  description: The parent category ID (optional).
                  example: "64f1b2c3e4b0a1b2c3d4e5f6"
              required:
                - name
      responses:
        '201':
          description: Category created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Category created successfully
                  data:
                    $ref: '#/definitions/Category'
        '400':
          description: Invalid input (e.g., missing or invalid `name`)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Name is required and must be a string.
        '404':
          description: Parent category not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Category not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

  /category-detail/{slug}:
    get:
      tags:
        - Category
      summary: Get category by slug
      description: |
        Retrieve a category by its unique slug.
      parameters:
        - in: path
          name: slug
          required: true
          type: string
          description: The slug of the category to retrieve.
          example: "electronics"
      responses:
        '200':
          description: Category found
          content:
            application/json:
              schema:
                $ref: '#/definitions/Category'
        '404':
          description: Category not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Category not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

  /update-category/{slug}:
    put:
      tags:
        - Category
      summary: Update a category by slug
      description: |
        Update a category with the provided details.
        The `slug` in the path is used to identify the category to update.
      parameters:
        - in: path
          name: slug
          required: true
          type: string
          description: The slug of the category to update.
          example: "electronics"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The updated name of the category.
                  example: "Updated Electronics"
                des:
                  type: string
                  description: The updated description of the category.
                  example: "Updated description for electronics."
                icon:
                  type: string
                  description: The updated icon for the category.
                  example: "fa-updated-electronics"
                parent:
                  type: string
                  description: The updated parent category ID (optional).
                  example: "64f1b2c3e4b0a1b2c3d4e5f6"
      responses:
        '200':
          description: Category updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Category updated successfully
                  data:
                    $ref: '#/definitions/Category'
        '404':
          description: Category not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Category not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

  /delete-category/{slug}:
    delete:
      tags:
        - Category
      summary: Delete a category by slug
      description: |
        Delete a category by its unique slug.
        This will also remove all its child categories.
      parameters:
        - in: path
          name: slug
          required: true
          type: string
          description: The slug of the category to delete.
          example: "electronics"
      responses:
        '200':
          description: Category deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Category deleted successfully
        '404':
          description: Category not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Category not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

  /change-category-status/{slug}:
    patch:
      tags:
        - Category
      summary: Change the status of a category by slug
      description: |
        Toggle the status of a category by its slug.
        This will activate or deactivate the category.
      parameters:
        - in: path
          name: slug
          required: true
          type: string
          description: The slug of the category to change status.
          example: "electronics"
      responses:
        '200':
          description: Category status changed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Category status changed successfully
                  data:
                    $ref: '#/definitions/Category'
        '404':
          description: Category not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Category not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error

definitions:
  Category:
    type: object
    properties:
      name:
        type: string
        example: "Electronics"
      des:
        type: string
        example: "All electronic gadgets and devices."
      icon:
        type: string
        example: "fa-electronics"
      parent:
        type: string
        example: "64f1b2c3e4b0a1b2c3d4e5f6"
      slug:
        type: string
        example: "electronics"
      parents:
        type: array
        items:
          type: string
        example: ["64f1b2c3e4b0a1b2c3d4e5f6"]
      status:
        type: boolean
        example: true